package app.event;

public enum ManagerEvent {

    LOGIN_SUCCESS,
    LOGIN_FAIL,
    CORE_INSTALL,
    CORE_INSTALL_FAILED,
    CORE_UPDATE,
    CORE_UPDATE_FAILED,
    CORE_START,
    CORE_START_FAILED,
    CORE_STOP,
    CORE_STOP_FAILED

}
